### ISSUE TITLE
Single 'contact' user breaks sample sheet generation

### ISSUE THREAD

**Issue by tanaes** [jdereus/labman#163]
```
AN ERROR HAS OCCURED!
Please copy the following into an issue in our github repository

Error
sequence item 0: expected str instance, NoneType found

Traceback
Traceback (most recent call last): 
File "/Users/jonsanders/Development/anaconda/envs/labman/lib/python3.6/site-packages/tornado/web.py", line 1510, in _execute result = method(*self.path_args, **self.path_kwargs) 
File "/Users/jonsanders/Development/anaconda/envs/labman/lib/python3.6/site-packages/tornado/web.py", line 2898, in wrapper return method(self, *args, **kwargs) 
File "/Users/jonsanders/Development/git_sw/labman/labman/gui/handlers/process_handlers/sequencing_process.py", line 60, in get text = process.generate_sample_sheet() 
File "/Users/jonsanders/Development/git_sw/labman/labman/db/process.py", line 2821, in generate_sample_sheet return self._generate_amplicon_sample_sheet() 
File "/Users/jonsanders/Development/git_sw/labman/labman/db/process.py", line 2795, in _generate_amplicon_sample_sheet contacts=contacts), 
File "/Users/jonsanders/Development/git_sw/labman/labman/db/process.py", line 2656, in _format_sample_sheet_comments sep, sep.join(x for x in sorted(contacts.keys())), 
TypeError: sequence item 0: expected str instance, NoneType found 

Request Info
```

**Comment by tanaes** [comment]
in further testing, this seems to be a problem with the 'LabmanSystem@labman.com' user. If that user is included in the contacts, it breaks the sample sheet generation.

**Comment by tanaes** [comment]
So this is coming from the fact that the db allows name to be empty, and in `list_users()` it is using `coalesce` to munge in the email address:

https://github.com/jdereus/labman/blob/12324bd181ccafe9b3dcf79b381e90c9d4567c97/labman/db/user.py#L34-L40

but when you call the `name` attribute directly, it returns `None`:

https://github.com/jdereus/labman/blob/12324bd181ccafe9b3dcf79b381e90c9d4567c97/labman/db/user.py#L113-L116

**Comment by tanaes** [comment]
@josenavas Do you think we can enforce presence of both name and email in User so this doesn't bite us in other places?

**Comment by josenavas** [comment]
Unfortunately not, that would break different parts of Qiita, as it is optional in there.

We should solve locally in this project, and I would suggest the best solution would be to use coalesce in the `name` property, so it always returns something there.
