### ISSUE TITLE
error when trying to save extraction plate

### ISSUE THREAD

**Issue by jdereus** [jdereus/labman#24]
this is using my extraction kit "7" and plate "jd_test_plate_1".  values should be checked before extraction button pressed.

AN ERROR HAS OCCURED!

Please copy the following into an issue in our github repository
Error

Error running SQL query: Query: INSERT INTO qiita.plate (external_id, plate_configuration_id) VALUES (%s, %s) RETURNING plate_id Arguments: ['gdna - jd_test_plate_1', 1] Error: duplicate key value violates unique constraint "idx_plate" DETAIL: Key (external_id)=(gdna - jd_test_plate_1) already exists.
Traceback

Traceback (most recent call last):
File "/home/pmapper/labman/labman/db/sql_connection.py", line 586, in _execute cur.execute(sql, sql_args)
File "/home/pmapper/.virtualenvs/labman/lib/python3.5/site-packages/psycopg2/extras.py", line 144, in execute return super(DictCursor, self).execute(query, vars)
psycopg2.IntegrityError: duplicate key value violates unique constraint "idx_plate" DETAIL: Key (external_id)=(gdna - jd_test_plate_1) already exists.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/pmapper/.virtualenvs/labman/lib/python3.5/site-packages/tornado/web.py", line 1509, in _execute result = method(*self.path_args, **self.path_kwargs)
File "/home/pmapper/.virtualenvs/labman/lib/python3.5/site-packages/tornado/web.py", line 2897, in wrapper return method(self, *args, **kwargs)
File "/home/pmapper/labman/labman/gui/handlers/process_handlers/gdna_extraction_process.py", line 40, in post ReagentComposition.from_external_id(kit), plates, volume)
File "/home/pmapper/labman/labman/db/process.py", line 427, in create plate_config)
File "/home/pmapper/labman/labman/db/plate.py", line 179, in create return cls(TRN.execute_fetchlast())
File "/home/pmapper/labman/labman/db/sql_connection.py", line 391, in wrapper return func(self, *args, **kwargs)
File "/home/pmapper/labman/labman/db/sql_connection.py", line 666, in execute_fetchlast res = self.execute()[-1]
File "/home/pmapper/labman/labman/db/sql_connection.py", line 391, in wrapper return func(self, *args, **kwargs)
File "/home/pmapper/labman/labman/db/sql_connection.py", line 643, in execute return self._execute()
File "/home/pmapper/labman/labman/db/sql_connection.py", line 590, in _execute self._raise_execution_error(sql, sql_args, e)
File "/home/pmapper/labman/labman/db/sql_connection.py", line 535, in _raise_execution_error % (sql, str(sql_args), str(error)))
ValueError: Error running SQL query: Query: INSERT INTO qiita.plate (external_id, plate_configuration_id) VALUES (%s, %s) RETURNING plate_id Arguments: ['gdna - jd_test_plate_1', 1] Error: duplicate key value violates unique constraint "idx_plate" DETAIL: Key (external_id)=(gdna - jd_test_plate_1) already exists.
Request Info

_cookies: Set-Cookie: CFID=Z2d1fkha6uvgtkj4wvgbnzclbmxuj9y4qm9ymv8wgbnrl4g2hha-1228638 Set-Cookie: CFTOKEN=Z2d1fkha6uvgtkj4wvgbnzclbmxuj9y4qm9ymv8wgbnrl4g2hha-73981556 Set-Cookie: __unam=aaacafd-15f6e0e0d65-474ffc59-6 Set-Cookie: __utma=57960238.307198039.1505239670.1505309995.1505309995.1 Set-Cookie: __utmc=57960238 Set-Cookie: __utmz="57960238.1505309995.1.1.utmcsr=a4.ucsd.edu|utmccn=(referral)|utmcmd=referral|utmcct=/tritON/profile/SAML2/Redirect/SSO" Set-Cookie: _ga=GA1.2.307198039.1505239670 Set-Cookie: jlinkappx="/employeeMyTimeEntry/index.htm" Set-Cookie: jlinkauthserver=bromberg Set-Cookie: jlinkserver=act Set-Cookie: jlinksessionidx=zecddd520b12f8082cd91f5264d0cc0f1 Set-Cookie: jssoserver=bromberg Set-Cookie: user=2|1:0|10:1515512270|4:user|24:ImpkZXJldXNAdWNzZC5lZHUi|bf1d6f1d38b392d1793a388a3845c99ae13bf604fb151348f4bdde7798369f04 Set-Cookie: xjlinkloginMyTimeEntry.User=OK Set-Cookie: xjlinkloginStaff.InquiryA4=OK
query_arguments: {}
remote_ip: 137.110.93.190
host: maptest.ucsd.edu:8080
arguments: {'plates': [b'["9"]'], 'volume': [b'3'], 'tool': [b'15'], 'robot': [b'6'], 'kit': [b'7']}
uri: /process/gdna_extraction
version: HTTP/1.1
_finish_time: None
connection:
_start_time: 1515517382.721669
body_arguments: {'plates': [b'["9"]'], 'volume': [b'3'], 'tool': [b'15'], 'robot': [b'6'], 'kit': [b'7']}
server_connection:
method: POST
host_name: maptest.ucsd.edu
body: b'robot=6&tool=15&kit=7&volume=3&plates=%5B%229%22%5D'
query:
files: {}
path: /process/gdna_extraction
headers: Accept-Language: en-US,en;q=0.5 X-Requested-With: XMLHttpRequest Accept-Encoding: gzip, deflate Referer: http://maptest.ucsd.edu:8080/process/gdna_extraction Content-Length: 51 Dnt: 1 Content-Type: application/x-www-form-urlencoded; charset=UTF-8 Accept: */* Host: maptest.ucsd.edu:8080 Connection: keep-alive User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:53.0) Gecko/20100101 Firefox/53.0 Cookie: _ga=GA1.2.307198039.1505239670; __utma=57960238.307198039.1505239670.1505309995.1505309995.1; __utmz=57960238.1505309995.1.1.utmcsr=a4.ucsd.edu|utmccn=(referral)|utmcmd=referral|utmcct=/tritON/profile/SAML2/Redirect/SSO; CFID=Z2d1fkha6uvgtkj4wvgbnzclbmxuj9y4qm9ymv8wgbnrl4g2hha-1228638; CFTOKEN=Z2d1fkha6uvgtkj4wvgbnzclbmxuj9y4qm9ymv8wgbnrl4g2hha-73981556; __unam=aaacafd-15f6e0e0d65-474ffc59-6; jlinkserver=act; jssoserver=bromberg; jlinksessionidx=zecddd520b12f8082cd91f5264d0cc0f1; jlinkappx=/employeeMyTimeEntry/index.htm; xjlinkloginStaff.InquiryA4=OK; jlinkauthserver=bromberg; xjlinkloginMyTimeEntry.User=OK; __utmc=57960238; user=2|1:0|10:1515512270|4:user|24:ImpkZXJldXNAdWNzZC5lZHUi|bf1d6f1d38b392d1793a388a3845c99ae13bf604fb151348f4bdde7798369f04
protocol: http

**Comment by adswafford** [comment]
Probably the same error but in case:
AN ERROR HAS OCCURED!
Please copy the following into an issue in our github repository

Error
Error running SQL query: Query: INSERT INTO qiita.reagent_composition (composition_id, reagent_composition_type_id, external_lot_id) VALUES (%s, %s, %s) RETURNING reagent_composition_id Arguments: [1350, 1, 'test'] Error: duplicate key value violates unique constraint "idx_reagent" DETAIL: Key (external_lot_id)=(test) already exists.

Traceback
Traceback (most recent call last): 
File "/home/pmapper/labman/labman/db/sql_connection.py", line 586, in _execute cur.execute(sql, sql_args) 
File "/home/pmapper/.virtualenvs/labman/lib/python3.5/site-packages/psycopg2/extras.py", line 144, in execute return super(DictCursor, self).execute(query, vars) 
psycopg2.IntegrityError: duplicate key value violates unique constraint "idx_reagent" DETAIL: Key (external_lot_id)=(test) already exists. 
During handling of the above exception, another exception occurred: 
Traceback (most recent call last): 
File "/home/pmapper/.virtualenvs/labman/lib/python3.5/site-packages/tornado/web.py", line 1509, in _execute result = method(*self.path_args, **self.path_kwargs) 
File "/home/pmapper/.virtualenvs/labman/lib/python3.5/site-packages/tornado/web.py", line 2897, in wrapper return method(self, *args, **kwargs) 
File "/home/pmapper/labman/labman/gui/handlers/composition_handlers/reagent_composition.py", line 32, in post self.current_user, external_id, volume, reagent_type) 
File "/home/pmapper/labman/labman/db/process.py", line 286, in create instance, tube, volume, reagent_type, external_id) 
File "/home/pmapper/labman/labman/db/composition.py", line 263, in create rc_id = TRN.execute_fetchlast() 
File "/home/pmapper/labman/labman/db/sql_connection.py", line 391, in wrapper return func(self, *args, **kwargs) 
File "/home/pmapper/labman/labman/db/sql_connection.py", line 666, in execute_fetchlast res = self.execute()[-1] 
File "/home/pmapper/labman/labman/db/sql_connection.py", line 391, in wrapper return func(self, *args, **kwargs) 
File "/home/pmapper/labman/labman/db/sql_connection.py", line 643, in execute return self._execute() 
File "/home/pmapper/labman/labman/db/sql_connection.py", line 590, in _execute self._raise_execution_error(sql, sql_args, e) 
File "/home/pmapper/labman/labman/db/sql_connection.py", line 535, in _raise_execution_error % (sql, str(sql_args), str(error))) 
ValueError: Error running SQL query: Query: INSERT INTO qiita.reagent_composition (composition_id, reagent_composition_type_id, external_lot_id) VALUES (%s, %s, %s) RETURNING reagent_composition_id Arguments: [1350, 1, 'test'] Error: duplicate key value violates unique constraint "idx_reagent" DETAIL: Key (external_lot_id)=(test) already exists. 

Request Info
_cookies: Set-Cookie: SID=15151062672558 Set-Cookie: __utma=57960238.1689508911.1515106271.1515106271.1515106271.1 Set-Cookie: __utmc=57960238 Set-Cookie: __utmz="57960238.1515106271.1.1.utmcsr=a4.ucsd.edu|utmccn=(referral)|utmcmd=referral|utmcct=/tritON/profile/SAML2/Redirect/SSO" Set-Cookie: _ga=GA1.2.1689508911.1515106271 Set-Cookie: _gid=GA1.2.2100488026.1515433054 Set-Cookie: jlinkappx="/marketplace-sso/signon" Set-Cookie: jlinkengads=engads Set-Cookie: jlinkserver=act Set-Cookie: jlinksessionidx=z14cb47ab346701b94acfed3c4f87f2c4 Set-Cookie: jssoserver=bromberg Set-Cookie: user=2|1:0|10:1515517343|4:user|28:ImFkc3dhZmZvcmRAdWNzZC5lZHUi|d8e28c8c8240c9a9420b5958a92c654e937d321df389346ef8bfb80b485568d5 Set-Cookie: xjlinkloginStaff.InquiryA4=OK
query_arguments: {}
remote_ip: 137.110.91.187
host: maptest.ucsd.edu:8080
arguments: {'volume': [b'100'], 'external_id': [b'test'], 'reagent_type': [b'extraction kit']}
uri: /composition/reagent
version: HTTP/1.1
_finish_time: None
connection: 
_start_time: 1515517871.5531924
body_arguments: {'volume': [b'100'], 'external_id': [b'test'], 'reagent_type': [b'extraction kit']}
server_connection: 
method: POST
host_name: maptest.ucsd.edu
body: b'external_id=test&volume=100&reagent_type=extraction+kit'
query: 
files: {}
path: /composition/reagent
headers: Accept-Language: en-US,en;q=0.9 X-Requested-With: XMLHttpRequest Accept-Encoding: gzip, deflate Referer: http://maptest.ucsd.edu:8080/process/gdna_extraction Content-Length: 55 Content-Type: application/x-www-form-urlencoded; charset=UTF-8 Origin: http://maptest.ucsd.edu:8080 Accept: */* Cookie: jlinkserver=act; jssoserver=bromberg; jlinkengads=engads; __utma=57960238.1689508911.1515106271.1515106271.1515106271.1; __utmc=57960238; __utmz=57960238.1515106271.1.1.utmcsr=a4.ucsd.edu|utmccn=(referral)|utmcmd=referral|utmcct=/tritON/profile/SAML2/Redirect/SSO; _ga=GA1.2.1689508911.1515106271; SID=15151062672558; jlinksessionidx=z14cb47ab346701b94acfed3c4f87f2c4; _gid=GA1.2.2100488026.1515433054; jlinkappx=/marketplace-sso/signon; xjlinkloginStaff.InquiryA4=OK; user=2|1:0|10:1515517343|4:user|28:ImFkc3dhZmZvcmRAdWNzZC5lZHUi|d8e28c8c8240c9a9420b5958a92c654e937d321df389346ef8bfb80b485568d5 Connection: keep-alive User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36 Host: maptest.ucsd.edu:8080 
protocol: http

**Comment by adswafford** [comment]
The issue appears to happen when no plates have been added so you may just need a catch to warn the users instead of crashing
