### ISSUE TITLE
Duplicate key error when pasting platemap into sample plating page

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/labman#272]
NB: So far only observable against qiita-rc database, not against labman test database.

` Error running SQL query: Query: INSERT INTO qiita.plate (external_id, plate_configuration_id) VALUES (%s, %s) RETURNING plate_id Arguments: ['Manary_9', '2'] Error: duplicate key value violates unique constraint "idx_plate" DETAIL: Key (external_id)=(Manary_9) already exists.`

Full error trace here:
[manary_9_plate_error[3].pdf](https://github.com/jdereus/labman/files/2237440/manary_9_plate_error.3.pdf)

**Comment by antgonza** [comment]
Sorry for multiple messages, note that this error is shows a few times in the logs but the specific one based on the example in the original opening of the issue is:
```
[E 180727 14:19:54 web:1670] Uncaught exception POST /process/sample_plating (137.110.53.215)
    HTTPServerRequest(protocol='https', host='qiita-rc.ucsd.edu:5573', method='POST', uri='/process/sample_plating', version='HTTP/1.1', remote_ip='137.110.53.215')
    Traceback (most recent call last):
      File "/home/qiita_test/labman/labman/db/sql_connection.py", line 586, in _execute
        cur.execute(sql, sql_args)
      File "/home/qiita_test/miniconda3/envs/labman/lib/python3.5/site-packages/psycopg2/extras.py", line 144, in execute
        return super(DictCursor, self).execute(query, vars)
    psycopg2.IntegrityError: duplicate key value violates unique constraint "idx_plate"
    DETAIL:  Key (external_id)=(Manary_9) already exists.
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/qiita_test/miniconda3/envs/labman/lib/python3.5/site-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/qiita_test/miniconda3/envs/labman/lib/python3.5/site-packages/tornado/web.py", line 3006, in wrapper
        return method(self, *args, **kwargs)
      File "/home/qiita_test/labman/labman/gui/handlers/process_handlers/sample_plating_process.py", line 24, in post
        user, PlateConfiguration(plate_config_id), plate_ext_id)
      File "/home/qiita_test/labman/labman/db/process.py", line 263, in create
        plate = plate_module.Plate.create(plate_ext_id, plate_config)
      File "/home/qiita_test/labman/labman/db/plate.py", line 286, in create
        return cls(TRN.execute_fetchlast())
      File "/home/qiita_test/labman/labman/db/sql_connection.py", line 391, in wrapper
        return func(self, *args, **kwargs)
      File "/home/qiita_test/labman/labman/db/sql_connection.py", line 666, in execute_fetchlast
        res = self.execute()[-1]
      File "/home/qiita_test/labman/labman/db/sql_connection.py", line 391, in wrapper
        return func(self, *args, **kwargs)
      File "/home/qiita_test/labman/labman/db/sql_connection.py", line 643, in execute
        return self._execute()
      File "/home/qiita_test/labman/labman/db/sql_connection.py", line 590, in _execute
        self._raise_execution_error(sql, sql_args, e)
      File "/home/qiita_test/labman/labman/db/sql_connection.py", line 535, in _raise_execution_error
        % (sql, str(sql_args), str(error)))
    ValueError: Error running SQL query:
    Query: INSERT INTO qiita.plate
                            (external_id, plate_configuration_id)
                        VALUES (%s, %s)
                        RETURNING plate_id
    Arguments: ['Manary_9', '2']
    Error: duplicate key value violates unique constraint "idx_plate"
    DETAIL:  Key (external_id)=(Manary_9) already exists.
```
