### ISSUE TITLE
Tube ID/Study ID issue

### ISSUE THREAD

**Issue by charles-cowart** [jdereus/labman#399]
AN ERROR HAS OCCURED!
Please copy the following into an issue in our github repository
Error
Error running SQL query: Query: SELECT tube_id_1_aa FROM qiita.sample_12164 WHERE sample_id = %s Arguments: ['12164.PM01.RECT.PRE'] Error: column "tube_id_1_aa" does not exist LINE 1: SELECT tube_id_1_aa ^
Traceback
Traceback (most recent call last): 
File "/home/labcontrol/labcontrol/labman/labman/db/sql_connection.py", line 586, in _execute cur.execute(sql, sql_args) 
File "/home/labcontrol/miniconda3/envs/labcontrol/lib/python3.7/site-packages/psycopg2/extras.py", line 141, in execute return super(DictCursor, self).execute(query, vars) 
psycopg2.ProgrammingError: column "tube_id_1_aa" does not exist LINE 1: SELECT tube_id_1_aa ^ 
During handling of the above exception, another exception occurred: 
Traceback (most recent call last): 
File "/home/labcontrol/miniconda3/envs/labcontrol/lib/python3.7/site-packages/tornado/web.py", line 1590, in _execute result = method(*self.path_args, **self.path_kwargs)
File "/home/labcontrol/miniconda3/envs/labcontrol/lib/python3.7/site-packages/tornado/web.py", line 3006, in wrapper return method(self, *args, **kwargs) 
File "/home/labcontrol/labcontrol/labman/labman/gui/handlers/plate.py", line 265, in get self.write(json_encode(plate_layout_handler_get_request(plate_id))) 
File "/home/labcontrol/labcontrol/labman/labman/gui/handlers/plate.py", line 254, in plate_layout_handler_get_request sample = composition.specimen_id 
File "/home/labcontrol/labcontrol/labman/labman/db/composition.py", line 578, in specimen_id return study.sample_id_to_specimen_id(self.sample_id) 
File "/home/labcontrol/labcontrol/labman/labman/db/study.py", line 175, in sample_id_to_specimen_id res = TRN.execute_fetchflatten() 
File "/home/labcontrol/labcontrol/labman/labman/db/sql_connection.py", line 391, in wrapper return func(self, *args, **kwargs) 
File "/home/labcontrol/labcontrol/labman/labman/db/sql_connection.py", line 735, in execute_fetchflatten return list(chain.from_iterable(self.execute()[idx])) 
File "/home/labcontrol/labcontrol/labman/labman/db/sql_connection.py", line 391, in wrapper return func(self, *args, **kwargs) 
File "/home/labcontrol/labcontrol/labman/labman/db/sql_connection.py", line 643, in execute return self._execute() 
File "/home/labcontrol/labcontrol/labman/labman/db/sql_connection.py", line 590, in _execute self._raise_execution_error(sql, sql_args, e) 
File "/home/labcontrol/labcontrol/labman/labman/db/sql_connection.py", line 535, in _raise_execution_error % (sql, str(sql_args), str(error))) 
ValueError: Error running SQL query: Query: SELECT tube_id_1_aa FROM qiita.sample_12164 WHERE sample_id = %s Arguments: ['12164.PM01.RECT.PRE'] Error: column "tube_id_1_aa" does not exist LINE 1: SELECT tube_id_1_aa ^ 
Request Info
method: GET
uri: /plate/56/layout
version: HTTP/1.1
headers: Connection: upgrade Host: labcontrol.ucsd.edu X-Real-Ip: 137.110.72.60 X-Forwarded-For: 137.110.72.60 Accept-Encoding: identity Accept: */* X-Requested-With: XMLHttpRequest User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 Referer: https://labcontrol.ucsd.edu/plate?process_id=47 Accept-Language: en-US,en;q=0.9 Cookie: CFID=Z2d1fkha6uvgtkj4wvgbnzclbmxuj9y4qm9ymv8wgbnrl4g2hha-1045438; CFTOKEN=Z2d1fkha6uvgtkj4wvgbnzclbmxuj9y4qm9ymv8wgbnrl4g2hha-67706839; __ar_v4=%7CEDBWQU6CRBF23I6ZRMDHY7%3A20180111%3A1%7CCGVYTWO55NF67CXFKVLNWC%3A20180111%3A1%7CNANHVAJGXBE3FE2E7PM2NR%3A20180111%3A1; _ga=GA1.2.107398166.1498752585; jlinkserver=act; jssoserver=discount; __utmc=57960238; jlinkauthserver=discount; jlinkpedgch=pedgch; jlinksessionidx=z09cf68373ac4119f1f0dc79646c8fb4d; xjlinkloginStaff.InquiryA4=OK; xjlinkloginMyTimeEntry.User=OK; user="2|1:0|10:1548884097|4:user|28:Imdoc211NDE0QGdtYWlsLmNvbSI=|87b9526adc1a87ebbe3a6863e387d4a0cdb87e71925b91420f36cefe5616865d"; __utma=57960238.107398166.1498752585.1548884462.1548964928.55; __utmz=57960238.1548964928.55.45.utmcsr=a5.ucsd.edu|utmccn=(referral)|utmcmd=referral|utmcct=/tritON/profile/SAML2/Redirect/SSO; jlinkappx=/marketplace-sso/signon 
body: b''
remote_ip: 127.0.0.1
protocol: https
host: labcontrol.ucsd.edu
host_name: labcontrol.ucsd.edu
files: {}
connection: 
server_connection: 
_start_time: 1549309238.272316
_finish_time: None
path: /plate/56/layout
query: 
arguments: {}
query_arguments: {}
body_arguments: {}
_cookies: Set-Cookie: CFID=Z2d1fkha6uvgtkj4wvgbnzclbmxuj9y4qm9ymv8wgbnrl4g2hha-1045438 Set-Cookie: CFTOKEN=Z2d1fkha6uvgtkj4wvgbnzclbmxuj9y4qm9ymv8wgbnrl4g2hha-67706839 Set-Cookie: __ar_v4=%7CEDBWQU6CRBF23I6ZRMDHY7%3A20180111%3A1%7CCGVYTWO55NF67CXFKVLNWC%3A20180111%3A1%7CNANHVAJGXBE3FE2E7PM2NR%3A20180111%3A1 Set-Cookie: __utma=57960238.107398166.1498752585.1548884462.1548964928.55 Set-Cookie: __utmc=57960238 Set-Cookie: __utmz="57960238.1548964928.55.45.utmcsr=a5.ucsd.edu|utmccn=(referral)|utmcmd=referral|utmcct=/tritON/profile/SAML2/Redirect/SSO" Set-Cookie: _ga=GA1.2.107398166.1498752585 Set-Cookie: jlinkappx="/marketplace-sso/signon" Set-Cookie: jlinkauthserver=discount Set-Cookie: jlinkpedgch=pedgch Set-Cookie: jlinkserver=act Set-Cookie: jlinksessionidx=z09cf68373ac4119f1f0dc79646c8fb4d Set-Cookie: jssoserver=discount Set-Cookie: user="2|1:0|10:1548884097|4:user|28:Imdoc211NDE0QGdtYWlsLmNvbSI=|87b9526adc1a87ebbe3a6863e387d4a0cdb87e71925b91420f36cefe5616865d" Set-Cookie: xjlinkloginMyTimeEntry.User=OK Set-Cookie: xjlinkloginStaff.InquiryA4=OK

**Comment by charles-cowart** [comment]
As Greg mentioned, the expected behavior is that a column can be set to be the ID, and will then be auto populated on entry. That doesn't appear to be happening with Tube ID set to be the column. MacKenzie and Greg are currently having to use the study id to avoid red fields.

**Comment by charles-cowart** [comment]
> Error running SQL query: Query: SELECT tube_id_1_aa FROM qiita.sample_12164 WHERE sample_id = %s Arguments: ['12164.PM01.RECT.PRE'] Error: column "tube_id_1_aa" does not exist LINE 1: SELECT tube_id_1_aa ^

This query should now be:

> SELECT sample_values->>'tube_id_1_aa' FROM qiita.sample_12164 WHERE sample_id = '12164.PM01.RECT.PRE';

as 'tube_id_1_aa' is now a field stored as JSONB. Currently locating the source of the query.

**Comment by charles-cowart** [comment]
Above error cannot be recreated. Plate involved has since been discarded, and is no longer accessible to the UI on labcontrol.ucsd.edu. Error could not be recreated creating new test plates with the same study (12164), on both maptest and labcontrol.ucsd.edu.

Interestingly, specimen_id was set for the above study to tube_id_1_aa in labcontrol, but not maptest. Hence the behavior when inserting data into cells was different, and as expected:

![image](https://user-images.githubusercontent.com/42684307/55524786-5e83bc00-5643-11e9-8d4b-33b67068b7e0.png)

Notice that maptest generates a pulldown with the study id prepending each recorded sample:

![image](https://user-images.githubusercontent.com/42684307/55524847-8f63f100-5643-11e9-9278-c5d4f02de7ad.png)

After changing the value of specimen_id to 'tube_id_1_aa', the study_ids are no longer prepended to the values in the pull-down menu:

![image](https://user-images.githubusercontent.com/42684307/55524899-bc180880-5643-11e9-8e2b-877f49960e5e.png)

The ID may still end up being shaded with a color, if the ID has been used in another location, etc.

Based on the above, I will tentatively close this issue, as it appears to have been incidental.
