### ISSUE TITLE
Silent 500 errors when plating samples

### ISSUE THREAD

**Issue by wasade** [jdereus/labman#405]
`maptest.ucsd.edu` presently has read issues with the `qiita.sample_10317` database table. This is not obvious to the user when plating samples as, in some cases the samples are flagged in red, in others, there is a blue stripe, and in others the samples appear valid (or no indication to suggest otherwise). 

This particular issue is present due to a 500 error that appears to result from a permissions issue reading a table (though, oddly, it is possible to read other tables in the schema as evidenced by assigning a study)

![Screen Shot 2019-03-26 at 4 46 26 PM](https://user-images.githubusercontent.com/474290/55040713-d1a78580-4fe6-11e9-81a2-7c7946b83fce.png)

```bash
AN ERROR HAS OCCURED!
Please copy the following into an issue in our github repository

Error
Error running SQL query: Query: SELECT sample_id FROM qiita.sample_10317 WHERE LOWER(sample_id) LIKE %s ORDER BY sample_id LIMIT %s Arguments: ['%10317.000004216%', 20] Error: permission denied for relation sample_10317

Traceback
Traceback (most recent call last): 
File "/home/pmapper/labcontrol/labman/labman/db/sql_connection.py", line 586, in _execute cur.execute(sql, sql_args) 
File "/home/pmapper/miniconda3/envs/labcontrol/lib/python3.5/site-packages/psycopg2/extras.py", line 141, in execute return super(DictCursor, self).execute(query, vars) 
psycopg2.ProgrammingError: permission denied for relation sample_10317 
During handling of the above exception, another exception occurred: 
Traceback (most recent call last): 
File "/home/pmapper/miniconda3/envs/labcontrol/lib/python3.5/site-packages/tornado/web.py", line 1590, in _execute result = method(*self.path_args, **self.path_kwargs) 
File "/home/pmapper/miniconda3/envs/labcontrol/lib/python3.5/site-packages/tornado/web.py", line 3006, in wrapper return method(self, *args, **kwargs) 
File "/home/pmapper/labcontrol/labman/labman/gui/handlers/study.py", line 53, in get res = list(study.samples(term, limit=20)) 
File "/home/pmapper/labcontrol/labman/labman/db/study.py", line 214, in samples return TRN.execute_fetchflatten() 
File "/home/pmapper/labcontrol/labman/labman/db/sql_connection.py", line 391, in wrapper return func(self, *args, **kwargs) 
File "/home/pmapper/labcontrol/labman/labman/db/sql_connection.py", line 735, in execute_fetchflatten return list(chain.from_iterable(self.execute()[idx])) 
File "/home/pmapper/labcontrol/labman/labman/db/sql_connection.py", line 391, in wrapper return func(self, *args, **kwargs) 
File "/home/pmapper/labcontrol/labman/labman/db/sql_connection.py", line 643, in execute return self._execute() 
File "/home/pmapper/labcontrol/labman/labman/db/sql_connection.py", line 590, in _execute self._raise_execution_error(sql, sql_args, e) 
File "/home/pmapper/labcontrol/labman/labman/db/sql_connection.py", line 535, in _raise_execution_error % (sql, str(sql_args), str(error))) 
ValueError: Error running SQL query: Query: SELECT sample_id FROM qiita.sample_10317 WHERE LOWER(sample_id) LIKE %s ORDER BY sample_id LIMIT %s Arguments: ['%10317.000004216%', 20] Error: permission denied for relation sample_10317 
```

**Comment by wasade** [comment]
I've been trying to work through this issue. I think the jQuery calls for testing terms need to be modified to pay attention to the HTTP status codes spit back by the API, which I believe requires performing AJAX calls instead. The code for the queries is [here](https://github.com/jdereus/labman/blob/master/labman/gui/static/js/plateViewer.js#L647-L674). 

However, I so far have not been successful on this over the last 2 hours of attempting to screw with the javascript... I've never used AJAX before, barely used javascript, and am rather confused by a host of what appear to be implicit variables in the code. This issue may make more sense for someone with jQuery/AJAX experience to take a poke at. Unassigning.

**Comment by AmandaBirmingham** [comment]
Note: whoever fixes this, see if the fix approach can also address the underlying issues in https://github.com/jdereus/labman/issues/385 which is technically closed but only because a kludge was implemented.
