### ISSUE TITLE
error on parse_quantify page

### ISSUE THREAD

**Issue by jdereus** [jdereus/labman#41]
with a .txt file provided by Greg.  10-20-2017_AG_163.txt

AN ERROR HAS OCCURED!

Please copy the following into an issue in our github repository
Error

setting an array element with a sequence.
Traceback

Traceback (most recent call last):
File "/home/pmapper/.virtualenvs/labman/lib/python3.5/site-packages/tornado/web.py", line 1509, in _execute result = method(*self.path_args, **self.path_kwargs)
File "/home/pmapper/.virtualenvs/labman/lib/python3.5/site-packages/tornado/web.py", line 2897, in wrapper return method(self, *args, **kwargs)
File "/home/pmapper/labman/labman/gui/handlers/process_handlers/quantification_process.py", line 34, in post concentrations = QuantificationProcess.parse(file_content)
File "/home/pmapper/labman/labman/db/process.py", line 709, in parse return np.asarray(data, dtype=np.float)
File "/home/pmapper/.virtualenvs/labman/lib/python3.5/site-packages/numpy/core/numeric.py", line 492, in asarray return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
Request Info

**Comment by josenavas** [comment]
Can you attach the file used? After talking with Jon on Thursday it turns out that the file-format specification and examples that I had were incorrect. In the development version I fixed it based on the file-format specification that Jon had described in his notebook. It would be useful to see if both specifications are the same.

**Comment by jdereus** [comment]
[10-20-2017_AG_163.txt](https://github.com/jdereus/labman/files/1635664/10-20-2017_AG_163.txt)

**Comment by josenavas** [comment]
Thanks - that is yet a 3rd different format, it is neither the one that I had neither the one that @tanaes had. AFAIK all those files are generated by the same plate reader, can we settle in a single format? We can get to an agreement during the code sprint later today.

**Comment by josenavas** [comment]
We have settle in a format - the current parser already parsers the format that we have settled.
