### ISSUE TITLE
Unit tests no longer work with default qiita install

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/labman#460]
As of PR https://github.com/jdereus/labman/pull/409 , the `labman/db/testing.py` (now `labcontrol/db/testing.py`) `reset_test_db` method requires the qiita client to be running on "https://localhost:8383", NOT (as previously) on the default "https://localhost:21174":

<img width="1019" alt="Screen Shot 2019-04-16 at 5 54 04 PM" src="https://user-images.githubusercontent.com/10677935/56253491-6eeb5c00-6071-11e9-8234-00bfced2e6a3.png">
 
Thus, a user who follows the set-up instructions in https://github.com/jdereus/labman/blob/master/README.md (which tell you to follow the qiita set-up instructions in https://github.com/biocore/qiita/blob/master/INSTALL.md , which sets up qiita on port 21174) and then tries to run the unit tests will get hundreds of errors along the lines of those shown at the bottom (ask me how I know :D )

I assume the change to port 8383 was made for a reason and changing it back isn't feasible, but we should at least update the https://github.com/jdereus/labman/blob/master/README.md to instruct the user (a) THAT they need to change the qiita port, and (b) HOW to do so.

```
Traceback (most recent call last):
  File "/Users/Birmingham/Applications/miniconda3/envs/labman/lib/python3.6/unittest/suite.py", line 259, in _tearDownPreviousClass
    tearDownClass()
  File "/Users/Birmingham/Work/Repositories/Labman/labman/labcontrol/db/testing.py", line 68, in tearDownClass
    reset_test_db()
  File "/Users/Birmingham/Work/Repositories/Labman/labman/labcontrol/db/testing.py", line 39, in reset_test_db
    server_cert=labcontrol.db.settings.labman_settings.qiita_server_cert)
  File "/Users/Birmingham/Applications/miniconda3/envs/labman/lib/python3.6/site-packages/qiita_client/qiita_client.py", line 178, in __init__
    self._fetch_token()
  File "/Users/Birmingham/Applications/miniconda3/envs/labman/lib/python3.6/site-packages/qiita_client/qiita_client.py", line 192, in _fetch_token
    data=data)
  File "/Users/Birmingham/Applications/miniconda3/envs/labman/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/Birmingham/Applications/miniconda3/envs/labman/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/Birmingham/Applications/miniconda3/envs/labman/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/Birmingham/Applications/miniconda3/envs/labman/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/Birmingham/Applications/miniconda3/envs/labman/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='localhost', port=8383): Max retries exceeded with url: /qiita_db/authenticate/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10ccc3278>: Failed to establish a new connection: [Errno 61] Connection refused',))
```

**Comment by AmandaBirmingham** [comment]
Fixed in https://github.com/jdereus/labman/pull/461
